### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not bool

### ISSUE THREAD

**Issue by Phulieu** [VainF/DeepLabV3Plus-Pytorch#28]
I work with Cityscapes dataset but when training there is a error like this :
Traceback (most recent call last):
  File "main.py", line 388, in <module>
    main()
  File "main.py", line 217, in main
    vis = Visualizer(port=opts.vis_port,
  File "I:\DeepLabV3Plus-Pytorch-master\utils\visualizer.py", line 14, in __init__
    ori_win = json.loads(ori_win)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not bool

**Comment by Angel0003** [comment]
遇到了和你同样的问题，请问你怎么解决的？

**Comment by Phulieu** [comment]
> 遇到了和你同样的问题，请问你怎么解决的？

I still can not detect the problem. 
Do you have any recommendations ??
And please speak in English.
Thank you

**Comment by fanjing136** [comment]
problem： TypeError: the JSON object must be str, bytes or bytearray, not bool
I have the same problem. How can I solve it?

**Comment by koujunxia** [comment]
How I have the same problem. How can I solve it?

**Comment by Lzz-kit** [comment]
I have the same problem. Can anyone answer that?  Many thanks

**Comment by VainF** [comment]
Fixed! Please try the latest version.
