### ISSUE TITLE
train --year 2007 failed

### ISSUE THREAD

**Issue by ynjiun** [VainF/DeepLabV3Plus-Pytorch#41]
Hi, while waiting to download PascalVOC2012.zip, I try to run 2007 dataset I already downloaded before.

When run, I got the following error message:

(segmentation) paul@tensor:~/segmentation/DeepLabV3Plus-Pytorch$ python main.py --model deeplabv3plus_mobilenet --enable_vis --vis_port 28333 --gpu_id 0 --year 2007 --crop_val --lr 0.01 --crop_size 513 --batch_size 16 --output_stride 16
Setting up a new session...
Device: cuda
Dataset: voc, Train set: 209, Val set: 213
[!] Retrain
/home/paul/segmentation/lib/python3.6/site-packages/torchvision/transforms/functional.py:387: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
/home/paul/segmentation/lib/python3.6/site-packages/torchvision/transforms/functional.py:387: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Epoch 1, Itrs 10/30000, Loss=1.980302
Traceback (most recent call last):
  File "main.py", line 390, in <module>
    main()
  File "main.py", line 342, in main
    outputs = model(images)
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paul/segmentation/DeepLabV3Plus-Pytorch/network/utils.py", line 16, in forward
    x = self.classifier(features)
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paul/segmentation/DeepLabV3Plus-Pytorch/network/_deeplab.py", line 49, in forward
    output_feature = self.aspp(feature['out'])
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paul/segmentation/DeepLabV3Plus-Pytorch/network/_deeplab.py", line 160, in forward
    res.append(conv(x))
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paul/segmentation/DeepLabV3Plus-Pytorch/network/_deeplab.py", line 130, in forward
    x = super(ASPPPooling, self).forward(x)
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 178, in forward
    self.eps,
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/functional.py", line 2279, in batch_norm
    _verify_batch_size(input.size())
  File "/home/paul/segmentation/lib/python3.6/site-packages/torch/nn/functional.py", line 2247, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

what should I do to fix this error? Thank you for your help.

**Comment by VainF** [comment]
Hi @ynjiun, please make sure that batch size>1 for training mode.

**Comment by ynjiun** [comment]
Hi VainF,

Thank you for your response. It turns out that for unknown reason if the batch_size is 16 or 15 or 13, it will report the error. But if I set batch_size 14 or 12, then it works. I don't know why. Any insights?

**Comment by timothylimyl** [comment]
@ynjiun,

if you set the train loader to `drop_last=True` , you will not face this problem. 16*13=208, leaving one image behind, should not work for 16/13 but should had work for 13.

@VainF ,

I think it will be best if you set the train loader to `drop_last=True` just in case.  Edit line: https://github.com/VainF/DeepLabV3Plus-Pytorch/blob/master/main.py#L236

 Currently, pytorch batchnorm for training is not smart enough to ignore single batch size with single value feature map and some user will face this problem if their batch size has a remainder of 1 from the dataset. 

For example, building a bigger backbone, I was forced to use batch_size=2 and on cityscapes, the error will pop up as the train set has 2975 images (leaving a remainder of 1 at the last load which causes the error).

**Comment by VainF** [comment]
Fixed! Thanks for your help.
